const data = [
    {
        id: 1,
        type: 'month',
        label: 'January',
        value: 'Jan',
    },
    {
        id: 2,
        type: 'month',
        label: 'Feburary',
        value: 'Feb',
    },
    {
        id: 3,
        type: 'month',
        label: 'March',
        value: 'Mar',
    },
    {
        id: 4,
        type: 'month',
        label: 'April',
        value: 'Apr',
    },
    {
        id: 5,
        type: 'month',
        label: 'May',
        value: 'May',
    },
    {
        id: 6,
        type: 'month',
        label: 'June',
        value: "Jun",
    },
    {
        id: 7,
        type: 'month',
        label: 'July',
        value: 'Jul',
    },
    {
        id: 8,
        type: 'month',
        label: 'August',
        value: 'Aug',
    },
    {
        id: 9,
        type: 'month',
        label: 'September',
        value: 'Sep',
    },
    {
        id: 10,
        type: 'month',
        label: 'October',
        value: 'Oct',
    },
    {
        id: 11,
        type: 'month',
        label: 'November',
        value: 'Nov',
    },
    {
        id: 12,
        type: 'month',
        label: 'December',
        value: 'Dec',
    },
    {
        id: 13,
        type: 'date',
        label: '1',
        value: '1st',
    },
    {
        id: 14,
        type: 'date',
        label: '2',
        value: '2nd',
    },
    {
        id: 15,
        type: 'date',
        label: '3',
        value: '3rd',
    },
    {
        id: 16,
        type: 'date',
        label: '4',
        value: '4th',
    },
    {
        id: 17,
        type: 'date',
        label: '5',
        value: '5th',
    },
    {
        id: 18,
        type: 'date',
        label: '6',
        value: '6th',
    },
    {
        id: 19,
        type: 'date',
        label: '7',
        value: '7th',
    },
    {
        id: 20,
        type: 'date',
        label: '8',
        value: '8th',
    },
    {
        id: 21,
        type: 'date',
        label: '9',
        value: '9th',
    },
    {
        id: 22,
        type: 'date',
        label: '10',
        value: '10th',
    },
    {
        id: 23,
        type: 'date',
        label: '11',
        value: '11th',
    },
    {
        id: 24,
        type: 'date',
        label: '12',
        value: '12th',
    },
    {
        id: 25,
        type: 'date',
        label: '13',
        value: '13th',
    },
    {
        id: 26,
        type: 'date',
        label: '14',
        value: '14th',
    },
    {
        id: 27,
        type: 'date',
        label: '15',
        value: '15th',
    },
    {
        id: 28,
        type: 'date',
        label: '16',
        value: '16th',
    },
    {
        id: 29,
        type: 'date',
        label: '17',
        value: '17th',
    },
    {
        id: 30,
        type: 'date',
        label: '18',
        value: '18th',
    },
    {
        id: 31,
        type: 'date',
        label: '19',
        value: '19th',
    },
    {
        id: 32,
        type: 'date',
        label: '20',
        value: '20th',
    },
    {
        id: 33,
        type: 'date',
        label: '21',
        value: '21st',
    },
    {
        id: 34,
        type: 'date',
        label: '22',
        value: '22nd',
    },
    {
        id: 35,
        type: 'date',
        label: '23',
        value: '23rd',
    },
    {
        id: 36,
        type: 'date',
        label: '24',
        value: '24th',
    },
    {
        id: 37,
        type: 'date',
        label: '25',
        value: '25th',
    },
    {
        id: 38,
        type: 'date',
        label: '26',
        value: '26th',
    },
    {
        id: 39,
        type: 'date',
        label: '27',
        value: '27th',
    },
    {
        id: 40,
        type: 'date',
        label: '28',
        value: '28th',
    },
    {
        id: 41,
        type: 'date',
        label: '29',
        value: '29th',
    },
    {
        id: 42,
        type: 'date',
        label: '30',
        value: '30th',
    },
    {
        id: 43,
        type: 'date',
        label: '31',
        value: '31st',
    }
]

export default data;